[package]
name = "mlt"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "2.0.11"
geozero = { version = "0.14", features = ["with-mvt"] }
prost = "0.13.5"
prost-types = "0.13.5"
indexmap = "2.7.1"
geo-types = "0.7.15"
fastpfor = { version = "0.6.2", features = ["cpp", "rust"] }

[build-dependencies]
prost-build = "0.13.5"

[lints.rust]
dead_code = "allow"
